# As part of my 100dayscoding I started the Python 3 at Codecademy.com. I have completed 44% of the Python 3 course and I am thinking to start a project.
# I will program something to extract information from the CNMV (National Securities Market Commission), but first I need to learn how to scrap information from website like CNMV. They do not have any kind of API to extract information...
